const express=require("express");
const router=express.Router();
const Blog=require("../models/blog");
const Comment=require("../models/comment");
router.get("/categories/technical/algorithms/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/algorithms");
      }
      else
      {
        res.render("comments/newcalgo",{blog:blog});
      }
    });
  });

  router.post("/categories/technical/algorithms/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/algorithms/"+blog._id);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/technical/algorithms/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/technical/algorithms/"+blog._id);
          }
        });
      }
    });
  });

  router.get("/categories/technical/architecture/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/architecture");
      }
      else
      {
        res.render("comments/newcalgo",{blog:blog});
      }
    });
  });

  router.post("/categories/technical/architecture/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/architecture/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/technical/architecture/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/technical/architecture/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/technical/dbms/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/dbms");
      }
      else
      {
        res.render("comments/newcalgo",{blog:blog});
      }
    });
  });

  router.post("/categories/technical/dbms/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/dbms/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/technical/dbms/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/technical/dbms/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/technical/ml/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/ml");
      }
      else
      {
        res.render("comments/newaralgo",{blog:blog});
      }
    });
  });

  router.post("/categories/technical/ml/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/ml/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/technical/ml/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/technical/ml/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/technical/net/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/net");
      }
      else
      {
        res.render("comments/newnet",{blog:blog});
      }
    });
  });

  router.post("/categories/technical/net/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/net/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/technical/net/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/technical/net/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/technical/soft/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/soft");
      }
      else
      {
        res.render("comments/newsoft",{blog:blog});
      }
    });
  });

  router.post("/categories/technical/soft/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/technical/soft/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/technical/soft/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/technical/soft/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/other/travel/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/travel");
      }
      else
      {
        res.render("comments/newother",{blog:blog});
      }
    });
  });

  router.post("/categories/other/travel/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/travel/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/other/travel/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/other/travel/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/other/food/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/food");
      }
      else
      {
        res.render("comments/newother",{blog:blog});
      }
    });
  });

  router.post("/categories/other/food/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/food/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/other/food/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/other/food/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/other/science/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/science");
      }
      else
      {
        res.render("comments/newother",{blog:blog});
      }
    });
  });

  router.post("/categories/other/science/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/science/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/other/science/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/other/science/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/other/medical/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/medical");
      }
      else
      {
        res.render("comments/newother",{blog:blog});
      }
    });
  });

  router.post("/categories/other/medical/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/medical/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/other/medical/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/other/medical/"+blog._id);
          }
        });
      }
    });
  });
  router.get("/categories/other/music/:id/comments/new",isLoggedIn,function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/music");
      }
      else
      {
        res.render("comments/newother",{blog:blog});
      }
    });
  });

  router.post("/categories/other/music/:id/comments",function(req,res){
    Blog.findById(req.params.id,function(err,blog){
      if(err)
      {
        res.redirect("/categories/other/music/"+blog._id);
        // console.log(err);
      }
      else
      {
        Comment.create(req.body.comment,function(err,comment){
          if(err)
          {
            res.redirect("/categories/other/music/"+blog._id);
          }
          else
          {
            comment.author.id=req.user._id;
            comment.author.username=req.user.username;
            comment.save();
            blog.comment.push(comment);
            blog.save();
            res.redirect("/categories/other/music/"+blog._id);
          }
        });
      }
    });
  });
  function isLoggedIn(req,res,next){
    if(req.isAuthenticated())
    {
      return next();
    }
    res.redirect("/login");
  };
  module.exports=router;
